from dataclasses import dataclass, asdict
from datetime import datetime
from pathlib import Path
import json
import logging


@dataclass
class Alert:
    timestamp: str
    level: str
    title: str
    message: str


class AlertManager:
    """
    Manage alerts generated by the application.
    """

    def __init__(self, logger=None, history_file="logs/alerts.json"):

        self.logger = logger or logging.getLogger("RansomwareDetector")
        self.history_file = Path(history_file)

        self.history_file.parent.mkdir(parents=True, exist_ok=True)

        self.history = []

    def _create_alert(self, level, title, message):

        alert = Alert(
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            level=level.upper(),
            title=title,
            message=message,
        )

        self.history.append(alert)

        self._log(alert)
        self._save()

        return alert

    def info(self, title, message):
        return self._create_alert("INFO", title, message)

    def warning(self, title, message):
        return self._create_alert("WARNING", title, message)

    def critical(self, title, message):
        return self._create_alert("CRITICAL", title, message)

    def _log(self, alert):

        text = f"[{alert.level}] {alert.title}: {alert.message}"

        if alert.level == "INFO":
            self.logger.info(text)

        elif alert.level == "WARNING":
            self.logger.warning(text)

        elif alert.level == "CRITICAL":
            self.logger.critical(text)

        else:
            self.logger.info(text)

    def _save(self):
        """
        Save alert history as JSON.
        """

        with self.history_file.open("w", encoding="utf-8") as file:

            json.dump(
                [asdict(alert) for alert in self.history],
                file,
                indent=4,
            )

    def get_history(self):
        """
        Return all alerts.
        """

        return list(self.history)

    def clear(self):
        """
        Remove all stored alerts.
        """

        self.history.clear()

        self._save()